
package com.kubris.qiss.soap.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EngineServices", targetNamespace = "http://engine.webservices.qengine/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EngineServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.RspCancelExec
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelExec", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.CancelExec")
    @ResponseWrapper(localName = "cancelExecResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.CancelExecResponse")
    public RspCancelExec cancelExec(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.RspCheckExecStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkExecStatus", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.CheckExecStatus")
    @ResponseWrapper(localName = "checkExecStatusResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.CheckExecStatusResponse")
    public RspCheckExecStatus checkExecStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.RspGetExecResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExecResult", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.GetExecResult")
    @ResponseWrapper(localName = "getExecResultResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.GetExecResultResponse")
    public RspGetExecResult getExecResult(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns wsdl.RspReqExecControlli
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reqExecControlli", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecControlli")
    @ResponseWrapper(localName = "reqExecControlliResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecControlliResponse")
    public RspReqExecControlli reqExecControlli(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns wsdl.RspReqExecTestControlli
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reqExecTestControlli", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestControlli")
    @ResponseWrapper(localName = "reqExecTestControlliResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestControlliResponse")
    public RspReqExecTestControlli reqExecTestControlli(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns wsdl.RspReqExecTestControllo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reqExecTestControllo", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestControllo")
    @ResponseWrapper(localName = "reqExecTestControlloResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestControlloResponse")
    public RspReqExecTestControllo reqExecTestControllo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.RspReqExecTestQuery
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reqExecTestQuery", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestQuery")
    @ResponseWrapper(localName = "reqExecTestQueryResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqExecTestQueryResponse")
    public RspReqExecTestQuery reqExecTestQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl.RspReqPlanDescriptionForTestQuery
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reqPlanDescriptionForTestQuery", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqPlanDescriptionForTestQuery")
    @ResponseWrapper(localName = "reqPlanDescriptionForTestQueryResponse", targetNamespace = "http://engine.webservices.qengine/", className = "wsdl.ReqPlanDescriptionForTestQueryResponse")
    public RspReqPlanDescriptionForTestQuery reqPlanDescriptionForTestQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
