
package com.kubris.qiss.soap.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EngineServicesService", targetNamespace = "http://engine.webservices.qengine/", wsdlLocation = "file:/C:/MyDocuments/EclipseNeon/QissScheduler/src/main/java/com/kubris/qiss/soap/fielqengine.wsdl")
public class EngineServicesService
    extends Service
{

    private final static URL ENGINESERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENGINESERVICESSERVICE_EXCEPTION;
    private final static QName ENGINESERVICESSERVICE_QNAME = new QName("http://engine.webservices.qengine/", "EngineServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/MyDocuments/EclipseNeon/QissScheduler/src/main/java/com/kubris/qiss/soap/fielqengine.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENGINESERVICESSERVICE_WSDL_LOCATION = url;
        ENGINESERVICESSERVICE_EXCEPTION = e;
    }

    public EngineServicesService() {
        super(__getWsdlLocation(), ENGINESERVICESSERVICE_QNAME);
    }

    public EngineServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENGINESERVICESSERVICE_QNAME, features);
    }

    public EngineServicesService(URL wsdlLocation) {
        super(wsdlLocation, ENGINESERVICESSERVICE_QNAME);
    }

    public EngineServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENGINESERVICESSERVICE_QNAME, features);
    }

    public EngineServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EngineServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EngineServices
     */
    @WebEndpoint(name = "EngineServicesPort")
    public EngineServices getEngineServicesPort() {
        return super.getPort(new QName("http://engine.webservices.qengine/", "EngineServicesPort"), EngineServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EngineServices
     */
    @WebEndpoint(name = "EngineServicesPort")
    public EngineServices getEngineServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://engine.webservices.qengine/", "EngineServicesPort"), EngineServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENGINESERVICESSERVICE_EXCEPTION!= null) {
            throw ENGINESERVICESSERVICE_EXCEPTION;
        }
        return ENGINESERVICESSERVICE_WSDL_LOCATION;
    }

}
